services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init-scripts/:/docker-entrypoint-initdb.d/
      
  minio:
    image: bitnami/minio
    restart: always
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_DEFAULT_BUCKETS: "audio"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio

  audio-files-backend:
    image: audio-files-backend
    restart: always
    container_name: audio-files-backend
    ports:
      - 3000:3000
    environment:
      FILE_COUNT_LIMIT: 3
      FILE_SIZE_LIMIT: 10000000
      MINIO_ENDPOINT: minio
      MINIO_AUDIO_BUCKET: audio
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MONGODB_HOST: mongo
      SESSION_SECRET: 12345678
      